# Generated by Django 4.2.2 on 2023-08-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomName',
            new_name='name',
        ),
    ]
